### ISSUE TITLE
cMMAgentOpsInsights not changing workspace ID and KEY

### ISSUE THREAD

**Issue by Andrpr** [rchaganti/DSCResources#16]
I'm looking at your DSC resource to use it within Azure DSC, but your custom DSC resource doesn't seem to change the workspace ID and Key.

Configuration MMAgentConfiguration 
{
    $OPSINSIGHTS_WS_ID = Get-AutomationVariable -Name "LA_WA_ID_02"
    $OPSINSIGHTS_WS_KEY = Get-AutomationVariable -Name "LA_WA_KEY_02"

    Import-DscResource -ModuleName cMMAgent

   Node OMSnode {
    cMMAgentOpInsights MMAgentOpInsights {
        WorkspaceID = $OPSINSIGHTS_WS_ID
        WorkspaceKey = $OPSINSIGHTS_WS_KEY
        Ensure = 'Present'
    }
  }
}

**Comment by rchaganti** [comment]
Thank you for reporting this issue. This module is moving to [OMSDsc](https://github.com/rchaganti/OMSDsc). I will push the Log Analytics resources end of next week. Please use them.

**Comment by rchaganti** [comment]
I released an preview version of the OMSDsc module. It is not on gallery yet but resolves this issue. 
https://github.com/rchaganti/OMSDsc/tree/dev/DSCResources

Please feel free to test this. I ma closing this issue.

**Comment by Andrpr** [comment]
Thank you, perfect…
